//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public System.Guid id_Facturas { get; set; }
        public string Folio { get; set; }
        public string Fecha { get; set; }
        public string FormaPago { get; set; }
        public Nullable<System.Guid> id_Cliente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
