//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaPagos
    {
        public System.Guid id_FacturaPagos { get; set; }
        public System.Guid id_Facturas { get; set; }
        public System.Guid id_Pagos { get; set; }
        public decimal Monto { get; set; }
        public decimal SaldoNuevo { get; set; }
        public string MetodoPago { get; set; }
        public decimal SaldoAnterior { get; set; }
    }
}
