//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fletes
    {
        public System.Guid Id_Flete { get; set; }
        public System.Guid Id_Tracto { get; set; }
        public System.Guid Id_Cliente { get; set; }
        public string Destino { get; set; }
        public string Origen { get; set; }
        public decimal Toneladas { get; set; }
        public decimal Precio { get; set; }
        public string Factura { get; set; }
        public decimal Pago { get; set; }
        public System.Guid Id_Usuario { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tractos Tractos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
