//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public System.Guid id_Pago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Fecha_Pago { get; set; }
        public string Forma_Pago { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Folio_Pago { get; set; }
        public string Cuenta_Banco { get; set; }
    }
}
