//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Fletes = new HashSet<Fletes>();
        }
    
        public System.Guid Id_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public decimal Comision { get; set; }
        public string Apellido01 { get; set; }
        public string Apellido02 { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> RolId { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fletes> Fletes { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
